// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1bmVywuFdCoEY6nhP8Z9MMD-7MmN0Vr8',
    appId: '1:796014529067:web:5733636d393dc88761b86e',
    messagingSenderId: '796014529067',
    projectId: 'flutter-pushnotification-d60d1',
    authDomain: 'flutter-pushnotification-d60d1.firebaseapp.com',
    storageBucket: 'flutter-pushnotification-d60d1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEegOj4sphx9lBMaTpqTZvDqmE4xqTfO4',
    appId: '1:796014529067:android:469bca5e82eaae6761b86e',
    messagingSenderId: '796014529067',
    projectId: 'flutter-pushnotification-d60d1',
    storageBucket: 'flutter-pushnotification-d60d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWhk6HTVMEW1w1Yvobb8M7EaaUv1VbLco',
    appId: '1:796014529067:ios:0913132fdf66664561b86e',
    messagingSenderId: '796014529067',
    projectId: 'flutter-pushnotification-d60d1',
    storageBucket: 'flutter-pushnotification-d60d1.appspot.com',
    iosBundleId: 'com.example.pushNotificationsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWhk6HTVMEW1w1Yvobb8M7EaaUv1VbLco',
    appId: '1:796014529067:ios:6c0adcd943eff6d161b86e',
    messagingSenderId: '796014529067',
    projectId: 'flutter-pushnotification-d60d1',
    storageBucket: 'flutter-pushnotification-d60d1.appspot.com',
    iosBundleId: 'com.example.pushNotificationsApp.RunnerTests',
  );
}
